msmtpq-ng: Fix testing for log directory
Signed-off-by: Daniel F. Dickinson <cshored@thecshore.com>

diff --git a/msmtpq-ng/msmtpq-ng-queue b/msmtpq-ng/msmtpq-ng-queue
--- a/msmtpq-ng/msmtpq-ng-queue
+++ b/msmtpq-ng/msmtpq-ng-queue
@@ -78,9 +78,9 @@ fi
 ## the queue log file - modify (or comment out) to taste  (but no quotes !!)
 [ -z "$LOG" ] && LOG=~/log/msmtp.queue.log
 [ -z "$MAXLOGLEVEL" ] && MAXLOGLEVEL=7		# Default to not displaying debug log messages
-[ -n "$LOG" ] && [ -d "$LOG" ] ||  {
+[ -n "$LOG" ] && [ -d "$(dirname $LOG)" ] ||  {
 	if [ "$LOG" != "syslog" ]; then
-		err '' "msmtpq-ng-queue : can't find msmtp queue directory [ $LOG ]" ''
+		err '' "msmtpq-ng-queue : can't find msmtp queue directory [ $(dirnmae $LOG) ]" ''
 	fi
 }
 
