msmtpq-ng-queue: Fix typo for missing log dir error message
Signed-off-by: Daniel F. Dickinson <cshored@thecshore.com>

diff --git a/msmtpq-ng/msmtpq-ng-queue b/msmtpq-ng/msmtpq-ng-queue
--- a/msmtpq-ng/msmtpq-ng-queue
+++ b/msmtpq-ng/msmtpq-ng-queue
@@ -71,16 +71,15 @@ fi
 ##     ( note that the LOG setting could be the same as the )
 ##     ( 'logfile' setting in .msmtprc - but there may be   )
 ##     ( some advantage in keeping the two logs separate    )
-##   if you don't want the log at all unset (don't just comment out) this var
-##     #LOG=~/log/msmtp.queue.log  -->  LOG=""
+##   if you don't want the log at all set this var to /dev/null
 ##     (doing so would be inadvisable under most conditions, however)
 ##
 ## the queue log file - modify (or comment out) to taste  (but no quotes !!)
 [ -z "$LOG" ] && LOG=~/log/msmtp.queue.log
 [ -z "$MAXLOGLEVEL" ] && MAXLOGLEVEL=7		# Default to not displaying debug log messages
-[ -n "$LOG" ] && [ -d "$(dirname $LOG)" ] ||  {
+[ -d "$(dirname $LOG)" ] ||  {
 	if [ "$LOG" != "syslog" ]; then
-		err '' "msmtpq-ng-queue : can't find msmtp queue directory [ $(dirnmae $LOG) ]" ''
+		err '' "msmtpq-ng-queue : can't find msmtp queue directory [ $(dirname $LOG) ]" ''
 	fi
 }
 
